apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: operator-guardrails
# Explicit placement binding name to avoid the missing metadata.name error
placementBindingDefaults:
  name: "operator-guardrails-binding" 
policyDefaults:
  namespace: policies
  # Ensures ConfigMaps are created before the policy templates that look them up
  consolidateManifests: false
  categories:
    - CM Configuration Management
  controls:
    - CM-2 Baseline Configuration
  # This default enforce action will apply to any future enforcing policies you add...
  remediationAction: enforce
  severity: medium
  standards:
    - NIST SP 800-53
  policySets:
    - operator-guardrails
policies:
  # This policy explicitly uses 'inform' to protect the audit policy
  - name: audit-operator-guardrails-inform
    remediationAction: inform 
    manifests:
      - path: input/auditexistingoperators/auditpolicy.yaml

  # This policy can enforce the supporting configurations
  - name: audit-operator-guardrails-enforce
    remediationAction: enforce
    manifests:
      - path: input/auditexistingoperators/configmaps.yaml
      - path: input/auditexistingoperators/vap.yaml
policySets:
  - name: operator-guardrails
    description: operator-guardrails
    placement:
      placementPath: placement.yaml
